### ISSUE TITLE
Genre game not displayed fully

### ISSUE THREAD

**Issue by wariobar** [djfumberger/retromega#14]
I have noticed that genre is not correctly displayed when the text is not short. Not sure if this issue happens with other languages, I do have my rom collection scrapped in spanish. Thank you in advance!

Regards,
Mario

![IMG_20210406_215510](https://user-images.githubusercontent.com/46299677/113772236-b8cd2100-9724-11eb-9869-7d25986c6b19.jpg)
![IMG_20210406_215642](https://user-images.githubusercontent.com/46299677/113772242-ba96e480-9724-11eb-9696-3f4eab721d40.jpg)

**Comment by djfumberger** [comment]
Ok thanks, fixed in 0f538acc9ecac7946f17ee8e2f741539a9158d85

**Comment by wariobar** [comment]
thanks a lot, man!
