### ISSUE TITLE
✨ Allow to come back at beginning of console's carousel

### ISSUE THREAD

**Issue by jeremyhalin** [djfumberger/retromega#4]
I think it could be nice, when we are on the last console slide to be able to come back at first slide just by continuing to scroll to right. I don't know if it's possible technically.

**Comment by djfumberger** [comment]
I'm generally not a big fan looping list / carousel UX, just because you can sometimes feel a bit lost when things repeat. But have had some other people ask too, so will consider it maybe as a preference to enable.

**Comment by jeremyhalin** [comment]
To be honest I really don't mind if you decide to not implement it. In my opinion you can put this feature at the very end of your priority list 😁
