### ISSUE TITLE
⚡️ It's laggy when scrolling fast in a larger games collection

### ISSUE THREAD

**Issue by jeremyhalin** [djfumberger/retromega#5]
Maybe there are optimisations we can do to make the theme smoother. If anyone has any insight about that it would be nice to share :)

I'm thinking about something like loading the game's image ONLY if the user "stays" on it for like 200 ms or so.

**Comment by djfumberger** [comment]
Yeah, I've prescaled all my covers to be max 320 wide , which gives scrolling performance like this: https://imgu r.com/a/gnVRGwn 

But getting feedback that this is probably not the norm.. 

The intent was to try and avoid the cover art feeling flickery or out of sync, but if most people have large cover art then probably not best to do at the expensive of scrolling speed, so I'll look into some optimisations here.

**Comment by djfumberger** [comment]
Hey, have added some updates to the way box art is handled, let me know if it improves your browsing etc. Thanks.

**Comment by jeremyhalin** [comment]
Just tested last version of retromega on Retroid Pocket 2 (Android 8.1).

Performance is amazing !!!!!
Great work 🎉
