### ISSUE TITLE
💡 Add to official Pegasus' theme gallery

### ISSUE THREAD

**Issue by jeremyhalin** [djfumberger/retromega#9]
Your theme is awesome ! I think it should be referenced on the [official Pegasus' theme gallery](https://pegasus-frontend.org/tools/themes/).

You can open an issue or create a pull request on the [official repo](https://github.com/mmatyas/pegasus-theme-gallery-db) add it to the list so more people can discover your great work.

**Comment by djfumberger** [comment]
Hey, yeah probably about time, so thanks for the reminder. I'll get it added soon.

**Comment by djfumberger** [comment]
Ok, added and created pull request - https://github.com/mmatyas/pegasus-theme-gallery-db/pull/7
